---

version: '2'

services:
  sut:
    build: .
    environment:
      - COVERAGE
      - RAILS_ENV
      - CC_TEST_REPORTER_ID
    command: make check
  ci-test:
    build: .
    environment:
      - RAILS_ENV
    command: make ci-test
